/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as ResultsResultIdRouteImport } from './routes/results.$resultId'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherCreateRouteImport } from './routes/teacher.create'
import { Route as ExamsExamIdIndexRouteImport } from './routes/exams.$examId.index'
import { Route as ExamsExamIdAttemptRouteImport } from './routes/exams.$examId.attempt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsResultIdRoute = ResultsResultIdRouteImport.update({
  id: '/results/$resultId',
  path: '/results/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCreateRoute = TeacherCreateRouteImport.update({
  id: '/teacher/create',
  path: '/teacher/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdIndexRoute = ExamsExamIdIndexRouteImport.update({
  id: '/exams/$examId/',
  path: '/exams/$examId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsExamIdAttemptRoute = ExamsExamIdAttemptRouteImport.update({
  id: '/exams/$examId/attempt',
  path: '/exams/$examId/attempt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/teacher/create': typeof TeacherCreateRoute
  '/exams/': typeof ExamsIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/exams/$examId/attempt': typeof ExamsExamIdAttemptRoute
  '/exams/$examId/': typeof ExamsExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/teacher/create': typeof TeacherCreateRoute
  '/exams': typeof ExamsIndexRoute
  '/results': typeof ResultsIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/exams/$examId/attempt': typeof ExamsExamIdAttemptRoute
  '/exams/$examId': typeof ExamsExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/results/$resultId': typeof ResultsResultIdRoute
  '/teacher/create': typeof TeacherCreateRoute
  '/exams/': typeof ExamsIndexRoute
  '/results/': typeof ResultsIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/exams/$examId/attempt': typeof ExamsExamIdAttemptRoute
  '/exams/$examId/': typeof ExamsExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/results/$resultId'
    | '/teacher/create'
    | '/exams/'
    | '/results/'
    | '/teacher/'
    | '/exams/$examId/attempt'
    | '/exams/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/results/$resultId'
    | '/teacher/create'
    | '/exams'
    | '/results'
    | '/teacher'
    | '/exams/$examId/attempt'
    | '/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/results/$resultId'
    | '/teacher/create'
    | '/exams/'
    | '/results/'
    | '/teacher/'
    | '/exams/$examId/attempt'
    | '/exams/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ResultsResultIdRoute: typeof ResultsResultIdRoute
  TeacherCreateRoute: typeof TeacherCreateRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  ExamsExamIdAttemptRoute: typeof ExamsExamIdAttemptRoute
  ExamsExamIdIndexRoute: typeof ExamsExamIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$resultId': {
      id: '/results/$resultId'
      path: '/results/$resultId'
      fullPath: '/results/$resultId'
      preLoaderRoute: typeof ResultsResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/create': {
      id: '/teacher/create'
      path: '/teacher/create'
      fullPath: '/teacher/create'
      preLoaderRoute: typeof TeacherCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/': {
      id: '/exams/$examId/'
      path: '/exams/$examId'
      fullPath: '/exams/$examId/'
      preLoaderRoute: typeof ExamsExamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$examId/attempt': {
      id: '/exams/$examId/attempt'
      path: '/exams/$examId/attempt'
      fullPath: '/exams/$examId/attempt'
      preLoaderRoute: typeof ExamsExamIdAttemptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ResultsResultIdRoute: ResultsResultIdRoute,
  TeacherCreateRoute: TeacherCreateRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  ExamsExamIdAttemptRoute: ExamsExamIdAttemptRoute,
  ExamsExamIdIndexRoute: ExamsExamIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
